spring:
  datasource:
    url: jdbc:h2:mem:parkingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # create, update, validate, none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
server:
  port: 8080
logging:
  level:
    org:
      springframework:
        security: DEBUG

